### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by sunxia233** [ShengcaiLiao/QAConv#1]
When I tried to run this code, I encountered an out of memory error. I want to know whether reducing the batchsize has a big impact on the accuracy of the experiment. And  may I ask at least how much GPU memory does this need to run?

**Comment by ShengcaiLiao** [comment]
Hi, thank you for the interest and the first issue. The memory usage can be found in the appendix of the latest arXiv paper. However, some configurations in the code need to be updated. I'm finalizing the code and will push a new update soon.

As for the batch size, reducing it to 16 results in a similar or slightly worse performance.

**Comment by ShengcaiLiao** [comment]
The code is updated, and now you can try it for a more efficient training and evaluation.

**Comment by haithanhp** [comment]
I run your code in **main.py** of TransMatcher but Out-Of-Memory issue is still there regarless of setting batch_size. Do you know how to modify it to make efficient?

**Comment by ShengcaiLiao** [comment]
What is the GPU card you used? I was using V100 with 32GB memory without issues, but I did not check those with lower memory.  You can try lower the batch size, --num_trans_layers, --dim_feedforward, and --neck.
