### ISSUE TITLE
Question about grad clipping in Graph Sampling Based Deep Metric Learning for Generalizable Person Re-Identification

### ISSUE THREAD

**Issue by hsfzxjy** [ShengcaiLiao/QAConv#12]
Thanks for the new paper. It's an impressive work!

I am curious about how bad it will be if not using grad clipping. Could you share some comparision of this?

**Comment by ShengcaiLiao** [comment]
Thanks for the interest. There are two bad cases. The first one is an increasing loss, until even NaN. The other one is a stuck loss at a certain value. The results of both cases are not meaningful.

**Comment by hsfzxjy** [comment]
Thanks for the clarification
