### ISSUE TITLE
python main_gs.py --dataset market --testset cuhk03_np_detected[,msmt] [--data-dir ./data] [--exp-dir ./Exp]

### ISSUE THREAD

**Issue by huangpan2507** [ShengcaiLiao/QAConv#18]
where is main_gs.py , I  cann't find it.  I wonder the  structure of the dataset , are these  datasets placed in the QAConv/data file?

**Comment by ShengcaiLiao** [comment]
It is now merged into main.py.

For some public datasets, use the definitions in QAConv/reid/datasets. Or define your own dataset in this folder.

**Comment by huangpan2507** [comment]
> It is now merged into main.py.
> 
> For some public datasets, use the definitions in QAConv/reid/datasets. Or define your own dataset in this folder.

Thank you for your patient answer, I will try it

**Comment by huangpan2507** [comment]
> It is now merged into main.py.
> 
> For some public datasets, use the definitions in QAConv/reid/datasets. Or define your own dataset in this folder.


Hi,  I'm confused about the cuhk.py  about  fpaths = sorted(glob(osp.join(self.images_dir, 1, '*.png')))   what's the  osp.join(xx, 1, *.png)   mean,  "1"?     What the function of cuhk.py ?  Thank  you.
the cuhk-np dataset I had download just like this:
cuhk03-np/
├── detected/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/
├── labeled/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/

**Comment by ShengcaiLiao** [comment]
I don't understand your question. It is "path" (e.g. train path or query path), not "1".

**Comment by huangpan2507** [comment]
> I don't understand your question. It is "path" (e.g. train path or query path), not "1".


In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '*.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '*.png')))  , I am confused about the datasets structure, can you make a list just like  it ? Thank you.
xx/
├── xxxx/
├────-------/xxx/
├────-------/xxx/
├────-------/xx/
├── xx/

**Comment by huangpan2507** [comment]
> I don't understand your question. It is "path" (e.g. train path or query path), not "1".

When I run    python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/Market/  --exp-dir ./Exp   ,the error read like that 
--------------------------------------------------------------------------------------------------------
File "/home/luotao/QAConv/reid/datasets/market.py", line 52, in load
      train_session_id, train_frame_id = map(np.array, zip(*list(map(frame_rule, [f for f, _, _ in self.train]))))    
ValueError: not enough values to unpack (expected 2, got 0)
---------------------------------------------------------------------------------------------------------
So I print(list(map(frame_rule, [f for f, _, _ in self.train]))), the output is [],  empty. So something happend in function  self.preprocess(self.train_path)

**Comment by huangpan2507** [comment]
>python main.py --dataset market --testset cuhk03_np_detected  --data-dir ./reid/datasets/  --exp-dir ./Exp
RuntimeError: CUDA out of memory. Tried to allocate 9.00 GiB (GPU 0; 11.77 GiB total capacity; 198.24 MiB already allocated; 7.10 GiB free; 2.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

batchsize=16

**Comment by ShengcaiLiao** [comment]
> > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> 
> In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/

For any dataset, the directory name should be the same with the dataset name. So for cuhk03_np_detected, you need to have a directory named cuhk03_np_detected under the data-dir, containing the three sub folders. That is,

data-dir/
├── market/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/
├── cuhk03_np_detected/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/
├── cuhk03_np_labeled/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/

**Comment by ShengcaiLiao** [comment]
> > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> 
> In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/

But I'm still confused how you get "1" but not "path" in the cuhk.py code.

**Comment by ShengcaiLiao** [comment]
> ## python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/ --exp-dir ./Exp
> RuntimeError: CUDA out of memory. Tried to allocate 9.00 GiB (GPU 0; 11.77 GiB total capacity; 198.24 MiB already allocated; 7.10 GiB free; 2.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF batchsize=16

I use V100 with 32GB of GPU memory. I'm not sure if 12GB memory is enough to run the training. By the way, do you encounter this during training or testing? During testing you can reduce some parameter values as described in the parameter help info in main.py.

**Comment by huangpan2507** [comment]
> 

python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/ --exp-dir ./Exp  
so this code is about training,  I change  the batchsize = 2, it is also out of cuda memory

**Comment by ShengcaiLiao** [comment]
> > 
> 
> python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/ --exp-dir ./Exp so this code is about training, I change the batchsize = 2, it is also out of cuda memory

This is not likely to be the problem in training. The code in main.py also performs testing. I guess it is raised in testing. Please reduce the values of the three parameters: --test_fea_batch, --test_gal_batch, --test_prob_batch.

**Comment by huangpan2507** [comment]
> > > 
> > 
> > 
> > python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/ --exp-dir ./Exp so this code is about training, I change the batchsize = 2, it is also out of cuda memory
> 
> This is not likely to be the problem in training. The code in main.py also performs testing. I guess it is raised in testing. Please reduce the values of the three parameters: --test_fea_batch, --test_gal_batch, --test_prob_batch.

It works for me! Thank you so much

**Comment by huangpan2507** [comment]
> > > 
> > 
> > 
> > python main.py --dataset market --testset cuhk03_np_detected --data-dir ./reid/datasets/ --exp-dir ./Exp so this code is about training, I change the batchsize = 2, it is also out of cuda memory
> 
> This is not likely to be the problem in training. The code in main.py also performs testing. I guess it is raised in testing. Please reduce the values of the three parameters: --test_fea_batch, --test_gal_batch, --test_prob_batch.


* Finished epoch 6 at lr=[5e-05, 0.0005, 0.0005]. Loss: 8.379. Acc: 78.21%. Training time: 1046 seconds.                  

* Finished epoch 7 at lr=[5e-05, 0.0005, 0.0005]. Loss: 7.911. Acc: 79.67%. Training time: 1221 seconds.                  

The learning converges at epoch 7.

Evaluate the learned model:
Traceback (most recent call last):
  File "main.py", line 394, in <module>
    main(parser.parse_args())
  File "main.py", line 257, in main
    get_test_data(test_name, args.data_dir, args.height, args.width, args.workers, args.test_fea_batch)
  File "main.py", line 83, in get_test_data
    dataset = datasets.create(dataname, root, combine_all=False)
  File "/home/luotao/QAConv/reid/datasets/__init__.py", line 35, in create
    return __factory[name](root, *args, **kwargs)
  File "/home/luotao/QAConv/reid/datasets/cuhk.py", line 18, in __init__
    self.load()
  File "/home/luotao/QAConv/reid/datasets/cuhk.py", line 41, in load
    self.train, self.num_train_ids = self.preprocess(self.train_path)
  File "/home/luotao/QAConv/reid/datasets/cuhk.py", line 24, in preprocess
    fpaths = sorted(glob(osp.join(self.images_dir, 1, '*.png')))
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'

so code  fpaths = sorted(glob(osp.join(self.images_dir, 1, '*.png')))  

> > > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> > 
> > 
> > In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/
> 
> For any dataset, the directory name should be the same with the dataset name. So for cuhk03_np_detected, you need to have a directory named cuhk03_np_detected under the data-dir, containing the three sub folders. That is,
> 
> data-dir/ ├── market/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_detected/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_labeled/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/

I got it ,thank you

**Comment by huangpan2507** [comment]
> > > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> > 
> > 
> > In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/
> 
> But I'm still confused how you get "1" but not "path" in the cuhk.py code.

I check the code, It is my fault, I guess maybe when I'm sleeping on the table during lunch break and accidentally pressed the keyboard, so it change to 1

**Comment by huangpan2507** [comment]
> > > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> > 
> > 
> > In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/
> 
> For any dataset, the directory name should be the same with the dataset name. So for cuhk03_np_detected, you need to have a directory named cuhk03_np_detected under the data-dir, containing the three sub folders. That is,
> 
> data-dir/ ├── market/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_detected/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_labeled/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/

what about msmt dataset struture 
Traceback (most recent call last):
  File "main.py", line 394, in <module>
    main(parser.parse_args())
  File "main.py", line 257, in main
    get_test_data(test_name, args.data_dir, args.height, args.width, args.workers, args.test_fea_batch)
  File "main.py", line 83, in get_test_data
    dataset = datasets.create(dataname, root, combine_all=False)
  File "/home/luotao/QAConv/reid/datasets/__init__.py", line 35, in create
    return __factory[name](root, *args, **kwargs)
  File "/home/luotao/QAConv/reid/datasets/msmt.py", line 22, in __init__
    self.load()
  File "/home/luotao/QAConv/reid/datasets/msmt.py", line 41, in load
    self.train, self.num_train_ids = self.preprocess(self.train_list_file)
  File "/home/luotao/QAConv/reid/datasets/msmt.py", line 25, in preprocess
    with open(osp.join(self.images_dir, list_file), 'r') as txt:
FileNotFoundError: [Errno 2] No such file or directory: './reid/datasets/msmt/list_train.txt

**Comment by huangpan2507** [comment]
> > > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> > 
> > 
> > In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/
> 
> For any dataset, the directory name should be the same with the dataset name. So for cuhk03_np_detected, you need to have a directory named cuhk03_np_detected under the data-dir, containing the three sub folders. That is,
> 
> data-dir/ ├── market/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_detected/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_labeled/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/


Compute similarity ...  Traceback (most recent call last):
  File "main.py", line 394, in <module>
    main(parser.parse_args())
  File "main.py", line 266, in main
    args.tau, args.sigma, args.K, args.alpha)
  File "/home/luotao/QAConv/reid/evaluators.py", line 186, in evaluate
    prob_fea, _ = extract_features(self.model, query_loader)
  File "/home/luotao/QAConv/reid/evaluators.py", line 42, in extract_features
    for i, (imgs, fnames, pids, _) in enumerate(data_loader):
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/luotao/QAConv/reid/utils/data/preprocessor.py", line 20, in __getitem__
    return self._get_single_item(indices)
  File "/home/luotao/QAConv/reid/utils/data/preprocessor.py", line 27, in _get_single_item
    img = Image.open(fpath).convert('RGB')
  File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './reid/datasets/msmt/test/0000/0000_000_01_0303morning_0015_0.jpg'

So， what the structure of the msmt17 dataset ？This dataset I download is：

data-dir/
├── msmt/
├────-------/bounding_box_test/
├────-------/bounding_box_train/
├────-------/query/
├────-------/list_gallery.txt
├────-------/list_query.txt
├────-------/list_train.txt
├────-------/list_val.txt
I rename bounding_box_test to test ，rename bounding_box_train to train.
data-dir/
├── msmt/
├────-------/test/
├────-------/train/
├────-------/query/
├────-------/list_gallery.txt
├────-------/list_query.txt
├────-------/list_train.txt
├────-------/list_val.txt

**Comment by huangpan2507** [comment]
> > > > I don't understand your question. It is "path" (e.g. train path or query path), not "1".
> > > 
> > > 
> > > In market.py , fpaths = sorted(glob(osp.join(self.images_dir, path, '_.jpg'))) but in cuhk.py it is fpaths = sorted(glob(osp.join(self.images_dir, 1, '_.png'))) , I am confused about the datasets structure, can you make a list just like it ? Thank you. CUHK/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xx/ ├── xxxx/ ├────-------/xxx/ ├────-------/xxx/ ├────-------/xxx/
> > 
> > 
> > For any dataset, the directory name should be the same with the dataset name. So for cuhk03_np_detected, you need to have a directory named cuhk03_np_detected under the data-dir, containing the three sub folders. That is,
> > data-dir/ ├── market/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_detected/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├── cuhk03_np_labeled/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/
> 
> ....
> ## Finished epoch 7 at lr=[5e-05, 0.0005, 0.0005]. Loss: 7.771. Acc: 80.07%. Training time: 1217 seconds.
> The learning converges at epoch 7.
> Evaluate the learned model:
> MSMT dataset loaded
> subset | # ids | # images
> 
> train | 1041 | 32621 query | 3060 | 11659 gallery | 3060 | 82161 Compute similarity ... Traceback (most recent call last): File "main.py", line 394, in main(parser.parse_args()) File "main.py", line 266, in main args.tau, args.sigma, args.K, args.alpha) File "/home/luotao/QAConv/reid/evaluators.py", line 186, in evaluate prob_fea, _ = extract_features(self.model, query_loader) File "/home/luotao/QAConv/reid/evaluators.py", line 42, in extract_features for i, (imgs, fnames, pids, _) in enumerate(data_loader): File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in **next** data = self._next_data() File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data return self._process_data(data) File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data data.reraise() File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/luotao/QAConv/reid/utils/data/preprocessor.py", line 20, in **getitem** return self._get_single_item(indices) File "/home/luotao/QAConv/reid/utils/data/preprocessor.py", line 27, in _get_single_item img = Image.open(fpath).convert('RGB') File "/home/luotao/anaconda3/envs/QAConv/lib/python3.6/site-packages/PIL/Image.py", line 2975, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: './reid/datasets/msmt/test/0000/0000_000_01_0303morning_0015_0.jpg'
> 
> So， what the structure of the msmt17 dataset ？This dataset I download is：
> 
> data-dir/ ├── msmt/ ├────-------/bounding_box_test/ ├────-------/bounding_box_train/ ├────-------/query/ ├────-------/list_gallery.txt ├────-------/list_query.txt ├────-------/list_train.txt ├────-------/list_val.txt I rename bounding_box_test to test ，rename bounding_box_train to train. data-dir/ ├── msmt/ ├────-------/test/ ├────-------/train/ ├────-------/query/ ├────-------/list_gallery.txt ├────-------/list_query.txt ├────-------/list_train.txt ├────-------/list_val.txt

OK， I see， the dataset we need is MSMT17_V1， NOT MSMT17_V2
data-dir/
├── MSMT17_V1/
├────-------/test/
├────-------/train/
├────-------/list_gallery.txt
├────-------/list_query.txt
├────-------/list_train.txt
├────-------/list_val.txt
