### ISSUE TITLE
想问一下作者是否有在单个数据集上做实验，结果如何？

### ISSUE THREAD

**Issue by hezhping** [ShengcaiLiao/QAConv#2]
非常感谢作者分享的代码，有个疑问，看论文上只提供了cross dataset的实验结果，从实验结果来看在cross dataset上范化性较好，不知道作者是否有在单个数据集上做实验，然后和MGN, strong baseline, JD/fast-reid(https://github.com/JDAI-CV/fast-reid)做过对比。

**Comment by ShengcaiLiao** [comment]
早期版本的代码有对比过，具体可以看arxiv上的第一个版本：https://arxiv.org/pdf/1904.10424v1.pdf

在没有用PCB结构的情况下，性能跟PCB差不多，略好一点。

除了QAConv的匹配头本身外，这个代码就是用的最基本的ResNet，训练策略和数据增广也都是最基本的，因此，一方面，跟strong baseline和fast-reid这些优化了一套训练技巧的代码不太好直接比较；另一方面，跟其他方法或代码其实是互补的，比如MGN的结构也可以直接替换ResNet，fast-reid的训练技巧也可以直接应用，等等，以此进一步提升QAConv。

**Comment by hezhping** [comment]
Thanks
