### ISSUE TITLE
Issues about evaluators.py

### ISSUE THREAD

**Issue by ArminLee** [ShengcaiLiao/QAConv#21]
I use Market as the training dataset and Duke as the test dataset, when I use --do_tlift, it shows that the size of tensor are not match.
![image](https://user-images.githubusercontent.com/45883628/150320831-2bb7c577-23c5-4565-ab96-89d041368b07.png)

In the evaluators.py document, line 212, the original dist size is 2228*17661 in Market dataset, and the size of dist_rerank is 2228*253 because the num_gal is not the same. The value of num_gal is the length of gallery images in the definition of line 189. However, it is redefined in line 204 as the size of gallery feature.

**Comment by ShengcaiLiao** [comment]
Hi, thanks for the report. This was a bug in the previous development. The code is now updated. Please see if your issue is resolved.

**Comment by ArminLee** [comment]
Thanks for your update, the issue has been solved!
