### ISSUE TITLE
Error about main.py

### ISSUE THREAD

**Issue by neko5358979** [ShengcaiLiao/QAConv#25]
I tried python main.py --dataset market --testset cuhk03_np_detected --data-dir /home/lzj/QAConv-master/data --exp-dir  home/lzj/QAConv-master/data ，and it shows error
![image](https://user-images.githubusercontent.com/98398912/161389661-3d901e83-46cf-46cd-a171-34ad2c43aa91.png)
I'm not sure if it's due to I passed the wrong command,though I checked the python main.py -h. And the path, /home/lzj/QAConv-master/data is where Market-1501 lies in. 
Thanks so much in advance!!!

**Comment by ShengcaiLiao** [comment]
Hi, it appears to be the dataset path issue. Please refer to https://github.com/ShengcaiLiao/QAConv/issues/18 for the setting of dataset path.
