### ISSUE TITLE
The Graph Sampling work 相关问题

### ISSUE THREAD

**Issue by zhustrong** [ShengcaiLiao/QAConv#26]
廖老师您好，读了您最近的The Graph Sampling work 论文，有两个问题不太清楚，想请教您一下，望您指点：
1. 在每一个epoch建图的时候，随机采样每个类的一张图片会不会造成比较大的偏差？
2. K=2处理梯度太小的问题时，会不会遇到完全采样不到的情况（以前在远大于学术数据集的业务数据集上遇到过着种问题，hardcase采样不到）

**Comment by ShengcaiLiao** [comment]
你好，谢谢关注。

1. 在训练刚开始的时候，偏差应该是有的。但刚开始训练也不太需要特别难的样本。随着训练的深入，类内会逐渐聚拢，那个时候随机采样就更有代表性了。另外这也是个计算复杂度和精度兼顾的问题，特别对于大规模数据集，随机采一张会更高效一些。尝试过采样多张，会有些提升，但提升不大了，说明采一张已经有一定的代表性了。

2. K=2你是说类内采样不到难样本？类间应该是跟K值关系不大。类内是有可能的，随机给两张不一定代表类内的最大间距。这个也得看训练数据集的构成情况了。

**Comment by zhustrong** [comment]
谢谢廖老师！
