### ISSUE TITLE
graph sampling的疑问

### ISSUE THREAD

**Issue by Terminator8758** [ShengcaiLiao/QAConv#29]
廖老师您好，想了解一下为什么graph sampling对于domain generalized re-id能够有很好的提升效果？以往的domain generalized re-id方法往往是采用domain invariant learning, style normalization等方式来解决这一任务，但graph sampling好像跟以往的方法思路不同，是通过加强hard mining的方式来改善domain generalization；对这一点有些不太理解，期待您的回复，谢谢！

**Comment by ShengcaiLiao** [comment]
你好。Graph Sampling（GS）本身并不是专门针对Domain Generalization（DG）提出来的，它需要结合一个DG算法。这里边DG效果好主要还是因为QAConv。在此基础上，GS对QAConv的提升主要是两个方面，一个是去掉了class memory，训练速度大幅提升了；另一方面是采样了更多困难样本后，模型的鉴别能力提升了，在已有的DG模型的基础上。

**Comment by Terminator8758** [comment]
谢谢；因为我的实验里，只在原模型(OSNet)的基础上，把原本的PK sampler改成Graph Sampler之后，跨数据集测试的性能也有较明显的提升，所以觉得好像Graph Sampling这个模块对domain generalization也是有效果的。

**Comment by ShengcaiLiao** [comment]
是的，主要是对训练时模型鉴别能力的提升，但前提还是需要有个本身DG性能还不错的模型，OSNet是可以的。

**Comment by JHYST** [comment]
可以麻烦分享一下OSNet-IBN-GS的代码吗？ @Terminator8758 @ShengcaiLiao ，谢谢两位老师！
