### ISSUE TITLE
还有两点疑问，一是为什么final_layer采用layer3，丢掉了最后的layer4？ 第二点就是为什么采用memery机制来缓存每个类的特征？

### ISSUE THREAD

**Issue by hezhping** [ShengcaiLiao/QAConv#3]
关于第一点，我的想法是这样的，本文的假设是，conv出来的特征保持了和原图空间一致的细节特征，因此，采用空间点对点的匹配可以一定程度上缓解对齐的问题，另外学习一个匹配函数（即最后全连接层），从而达到'query adaptive'的目的，而layer4出来的特征可能失去了一定的局部细节，甚至损失了特征的空间一致性。
关于第二点，我有个不成熟的想法是，训练时在mini batch内部两两匹配，然后分类或者metric learning的方式训练， 这样的话，训练与测试就完全一致，也不需要memery来存储每个类的feature map，这样，更灵活，更能够适应工业级的大规模数据集。

**Comment by ShengcaiLiao** [comment]
挺好的问题。

关于第一点你的理解是对的，论文5.1节里也解释了一下。论文3.3节的最后一句也是相关的解释：局部细节很重要。

关于第二点，缓存每个类的特征是为了全局训练，对于特征的鉴别性和训练的收敛速度应该都有帮助。至于你说的minibatch内部两两匹配，早期的研究里比较过，class memory有7%-10%的Rank1提升，4%-7%的mAP提升。这种pairwise的方式采样效率是比较低的，因为采样空间有N^2。这点可以参考arXiv论文v1版3.3节的开头有解释。

至于大规模数据集的训练，其实也还好，每1GB显存能放1万多类样本的特征图，而且class memory不是可学习的参数，可以不必全程占用显卡。
