### ISSUE TITLE
关于s=1

### ISSUE THREAD

**Issue by pSGAme** [ShengcaiLiao/QAConv#30]
廖老师您好，我想问一下关于s的取值问题。  您论文提到为了效率选择了s=1， 我是这么理解的，在不使用classmemory 而是使用pair wise match的情况下， 做一次QAconv的时间复杂度为O(  B^2 * (HW)^2 * s )。 按照时间复杂度来的化， s取值的大一点或者小小一点感觉没有多影响。 但是，当s=1的时候，可以直接使用矩阵乘法，然后又因为矩阵乘法做了大量的优化，所以实际的时间大大缩短了。所以最终s=1. 不知我的理解是否有问题，望老师您赐教！

**Comment by ShengcaiLiao** [comment]
你好。s在这里也是个平方，实际影响还是挺明显的，比如s=3就多了9倍的计算量。另外，以前的实验发现实际增大s所带来的性能提升也不明显。我后来的理解是，尺度的影响其实已经在前面的特征图提取里已经有所体现了，所以QAConv里的卷积核尺度就没那么必要了。比如特征图的最后一层的每个像素点都通常已经有很大的感受野了，另外最后一层neck卷积也可以调整大小，如果有需要让QAConv的匹配增大感受野的话。

**Comment by pSGAme** [comment]
嗯嗯，是s的平方。   谢谢老师
