### ISSUE TITLE
OSNet-IBN-GS代码

### ISSUE THREAD

**Issue by JHYST** [ShengcaiLiao/QAConv#33]
可以麻烦分享一下OSNet-IBN-GS的代码吗？谢谢老师！

**Comment by ShengcaiLiao** [comment]
你好，发个邮件给我，我发给你

**Comment by JHYST** [comment]
1469692674@qq.com,谢谢老师！

**Comment by JHYST** [comment]
***@***.***谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShengcaiLiao/QAConv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShengcaiLiao/QAConv] OSNet-IBN-GS代码 (Issue #33)





 
你好，发个邮件给我，我发给你
