### ISSUE TITLE
多源域训练/目标域测试

### ISSUE THREAD

**Issue by Xiaofu233** [ShengcaiLiao/QAConv#34]
廖老师，您好：
       请问QAConv系列工作是不是只适配cross-domain设定，即单源域和单目标域，在多源域和多目标域时能否使用呢？

谢谢！

**Comment by ShengcaiLiao** [comment]
你好，首先多目标域是没有问题的，论文里展示的结果都是单目标域训练出一个模型后，直接在多个目标域上分别测试的，这本来就是generalizable person re-identification的目标：模型训练好之后能到处拿去直接用。

对于多源域来说，QAConv这些工作也是能简单地直接应用的：把多源域数据汇总后当单源域一起训练就好了。论文附录里有一些多源域的结果，另外后续的一些论文也都有把QAConv应用在多源域进行比较（只不过多数对比的只是QAConv v1.0版本，即ECCV 2020的版本）。我们自己也有进一步对比QAConv-GS，例如在[TAL](https://arxiv.org/abs/2111.14290)的工作里，我们发现直接应用QAConv-GS在多源域里效果就挺好了，多数情况下比M^3L和MetaBIN好不少。TransMatcher应该更好。

相对来说，能用在单源域的算法，通用性会更好一些，因为扩展到多源域只需要简单地汇总一下训练数据。当然，进一步地考虑不同域之间的差异性可能能进一步地提升。
