### ISSUE TITLE
Unstable results

### ISSUE THREAD

**Issue by Checkmate986212** [ShengcaiLiao/QAConv#4]
Hi, 
Thanks for sharing your code.
However, I ran your code twice and get quite different results. Maybe due to random seed?
So did you set a fixed random seed when you train the model?

**Comment by ShengcaiLiao** [comment]
Yes, there could be some variations in results due to different random seeds. I tried to fix everything including the random seeds, which was better in stability, but the results were still not exactly reproducible. This is a common issue for almost all deep learning codes I think. So the only pratice suggested is to run the code several times.

**Comment by Checkmate986212** [comment]
Actually, in my experience, in other works,  random seed is usually fixed to 0 or others, and it is acceptable to have a variation of 1-2% in mAP and R1.
While in your code, I got a 4% variation about mAP, so I think it's too large.
How do you get your published results, and how many times have you experimented?

**Comment by ShengcaiLiao** [comment]
I usually run four times for all methods (including my baselines and ablation studies) and get the best results respectively for a fair comparison. 

Simply fixing random seeds does not mean stable results. There are still variations and sometimes large. Different initiallizations may also mean different good or bad starts for different algorithms. It is better to have algorithms explore more possibilities and report the average results and standard deviations, though not a common pratice in the community now.

Note that in this code we only test the final results, but in many codes they test every epoch and report the best results, which also contributes to stability but it is not a good practice too.

**Comment by Checkmate986212** [comment]
Yeah, you are right.

Besides, I used the old version of your code. Is that version something wrong?

**Comment by ShengcaiLiao** [comment]
I'm not sure which version you use, and I cannot remember what have been exactly changed among different versions. In a rough impression I think they should be fine in accuracy. However, you'd better use the current version, which is especially efficient in running speed and memory usage.

**Comment by Checkmate986212** [comment]
Hi Shengcai,
Another question :
I really wonder about the memory usage of testing MSMT17. I used 8 1080Ti, but still out of memory.

**Comment by ShengcaiLiao** [comment]
Do you mean the current code? For the current code and the default parameters it should be fine for testing MSMT17 in 1-2 1080Ti's. I don't have 1080Ti and so I'm not quite sure, though. If OOM still occurs, please reduce the related arguments regarding memory.

Let me test on a Titan Xp and get back to you later.

**Comment by ShengcaiLiao** [comment]
I've tried on a single Titan Xp. For the current code and the default parameters, testing on MSMT17 is fine, with a GPU memory usage of around 6.9GB.

**Comment by ShengcaiLiao** [comment]
Again, please use the latest code, which is optimized for speed and memory usage.

**Comment by ShengcaiLiao** [comment]
The current code is now more stable in producing results.
