### ISSUE TITLE
卷积核的output channel 为什么是h*w 呢

### ISSUE THREAD

**Issue by pansanity666** [ShengcaiLiao/QAConv#5]
作者您好，关于卷积核的output channel我有一点疑问：
按照个人理解， output channel 应该是 (h//s)*(w//s)? 是不是论文里打错了呀？还是我理解错了-0-

**Comment by ShengcaiLiao** [comment]
论文里的h和w是指feature map大小，不是图像大小。

**Comment by pansanity666** [comment]
> 论文里的h和w是指feature map大小，不是图像大小。
感谢回答～
我明白是feature map大小，按照您论文表达的意思，output channel的维度是query feature map里[s,s]卷积核的数量吧？我的理解，当s=1的时候是h*w,但是s>1的时候就不是了吧

**Comment by ShengcaiLiao** [comment]
s>1的时候output channel是不变的。跟正常卷积一样，输出的特征维度跟卷积核的大小无关。

**Comment by jingyut** [comment]
作者您好，看了回答有点疑惑，输出的channel数不是等于卷积核的数量吗？难道s变化不会影响卷积核的数量吗？

**Comment by ShengcaiLiao** [comment]
s变化不会影响卷积核的数量，feature map上的每个像素点邻域都会形成一个s*s大小的卷积核。当然，边界需要pad。

**Comment by jingyut** [comment]
谢谢，明白了！
