### ISSUE TITLE
训练非常慢！

### ISSUE THREAD

**Issue by zengwb-lx** [ShengcaiLiao/QAConv#7]
你好，我使用2块2080TI训练30W数据，64 batch_size 并且使用了fp16来加速训练，但是一个epoch训练了半个多小时才到511 iter，这正常吗？
Epoch: [1][511/4714] 455Time 2.620 (2.646)ec 0.0Data 0.001 (0.002)	Loss 456.984 (520.544)	Prec 0.00% (0.00%)

**Comment by ShengcaiLiao** [comment]
应该正常，速度慢主要跟类别数有关，因为class memory的遍历卷积比较费时。最近在研究大数据上如何加速，目前还没有达到加速的同时准确性相差不多。

**Comment by ShengcaiLiao** [comment]
现在训练速度快一些，训练整个MSMT（4101类，126441张图，15个epochs）在单张V100 GPU上只用了不到17个小时。

**Comment by ShengcaiLiao** [comment]
现在[QAConv 2.0](https://github.com/ShengcaiLiao/QAConv/releases/tag/v2.0)训练速度很快了。在MSMT全集上（4101类，12万图像）单卡训练15个epoch只需要3.88小时。在RandPerson上（8000类，13万图像）单卡训练4个epoch只需要1.84小时。在UnrealPerson上（6799类，125万图像）单卡训练4个epoch只需要1.67小时。

**Comment by huangpan2507** [comment]
> 现在[QAConv 2.0](https://github.com/ShengcaiLiao/QAConv/releases/tag/v2.0)训练速度很快了。在MSMT全集上（4101类，12万图像）单卡训练15个epoch只需要3.88小时。在RandPerson上（8000类，13万图像）单卡训练4个epoch只需要1.84小时。在UnrealPerson上（6799类，125万图像）单卡训练4个epoch只需要1.67小时。


是要跑60个epoch吧

**Comment by ShengcaiLiao** [comment]
> 

2.0只要跑15个epoch，虚拟数据库4个epoch。2.1版增加了自动控制epoch数，大部分公开数据库训练需要4-20个epoch。

**Comment by huangpan2507** [comment]
> > 
> 
> 2.0只要跑15个epoch，虚拟数据库4个epoch。2.1版增加了自动控制epoch数，大部分公开数据库训练需要4-20个epoch。
可以可以，之前跑其他人的需要训练6天，太久了
